tipo uppercase
notepad0n11n3/hyperblog pull request #1
Opened 2022-11-11 22:57 UTC by notepad0n11n3

pull request, tildes por html

2022-11-11 23:01 UTC, ellewen requested changes
se requiere entidades html

2022-11-14 03:58 UTC, notepad0n11n3 commented
cambios hechos, dame el merge.

2022-11-14 03:58 UTC, merged

2022-11-14 03:59 UTC, ellewen commented
lol

2022-11-16 05:07 UTC, ellewen commented
xd

2022-11-18 21:12 UTC, ellewen commented
o